steps:
- task: Docker@0
  displayName: 'Build an image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerFile: Dockerfile
    imageName: 'test-repo:latest'

steps:
- task: PrismaCloud.build-release-task.custom-build-release-task.prisma-cloud-compute-scan@3
  displayName: 'Prisma Cloud Compute Scan'
  inputs:
    twistlockService: 'Compute SaaS'
    artifact: 'test-repo:latest'
