resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: Docker@0
    displayName: Build an image
    inputs:
      containerregistrytype: Container Registry
      dockerFile: Dockerfile
      imageName: dtw-AZDO:latest
  - task: prisma-cloud-compute-scan@3
    displayName: Prisma Cloud Compute Scan
    inputs:
      twistlockService: 'PCC SaaS Console'
      artifact: dtw-AZDO:latest